-- begin NEWSAPP_EMPLOYEE
alter table NEWSAPP_EMPLOYEE add constraint FK_NEWSAPP_EMPLOYEE_ON_USER foreign key (USER_ID) references SEC_USER(ID)^
create index IDX_NEWSAPP_EMPLOYEE_ON_USER on NEWSAPP_EMPLOYEE (USER_ID)^
-- end NEWSAPP_EMPLOYEE
-- begin NEWSAPP_NEWS_CATEGORY
alter table NEWSAPP_NEWS_CATEGORY add constraint FK_NEWSAPP_NEWS_CATEGORY_ON_AUTHOR foreign key (AUTHOR_ID) references NEWSAPP_EMPLOYEE(ID)^
create index IDX_NEWSAPP_NEWS_CATEGORY_ON_AUTHOR on NEWSAPP_NEWS_CATEGORY (AUTHOR_ID)^
-- end NEWSAPP_NEWS_CATEGORY
-- begin NEWSAPP_NEWS
alter table NEWSAPP_NEWS add constraint FK_NEWSAPP_NEWS_ON_AUTHOR foreign key (AUTHOR_ID) references NEWSAPP_EMPLOYEE(ID)^
alter table NEWSAPP_NEWS add constraint FK_NEWSAPP_NEWS_ON_CATEGORY foreign key (CATEGORY_ID) references NEWSAPP_NEWS_CATEGORY(ID)^
create index IDX_NEWSAPP_NEWS_ON_AUTHOR on NEWSAPP_NEWS (AUTHOR_ID)^
create index IDX_NEWSAPP_NEWS_ON_CATEGORY on NEWSAPP_NEWS (CATEGORY_ID)^
-- end NEWSAPP_NEWS
-- begin NEWSAPP_NEWS_CATEGORY_EMPLOYEE_LINK
alter table NEWSAPP_NEWS_CATEGORY_EMPLOYEE_LINK add constraint FK_NEWCATEMP_ON_NEWS_CATEGORY foreign key (NEWS_CATEGORY_ID) references NEWSAPP_NEWS_CATEGORY(ID)^
alter table NEWSAPP_NEWS_CATEGORY_EMPLOYEE_LINK add constraint FK_NEWCATEMP_ON_EMPLOYEE foreign key (EMPLOYEE_ID) references NEWSAPP_EMPLOYEE(ID)^
-- end NEWSAPP_NEWS_CATEGORY_EMPLOYEE_LINK
